### ISSUE TITLE
Error connecting when use socket

### ISSUE THREAD

**Issue by HectorValencia** [Napsty/check_mysql_slavestatus#14]
To success conection i had to add "passoword" variable in "ConnectionResult"; in the socket section. Like this:

  ConnectionResult=$(mysql ${optfile} ${socket} ${user} -p"${password}" -e "SHOW SLAVE ${connection} STATUS ${channel}\G" 2>&1)

**Comment by Napsty** [comment]
Can you show how you used the plugin on the cmd line please?

**Comment by HectorValencia** [comment]
/usr/local/nagios/libexec/check_mysql_slavestatus.sh -Hlocalhost -unagios -p"password" -S"/database/mysql/mysql.sock" -C channel-db -w 900 -c 1800

**Comment by Napsty** [comment]
Thanks for showing the full command. You must **either use `-H` or `-S`** to connect to the MySQL server.
See documentation (https://www.claudiokuenzler.com/monitoring-plugins/check_mysql_slavestatus.php):

> 2: Unless defined in the options file, a host/ip address to connect to (-H) or a local socket (-S) is required.
3: When using -H or -S to connect to MySQL, credentials are required.

But the plugin should inform about this. Will do a code change for this.
