### ISSUE TITLE
Updated privileges for MariaDB 10.5+

### ISSUE THREAD

**Issue by aj-gh** [Napsty/check_mysql_slavestatus#17]
Since MariaDB 10.5+ the `REPLICA MONITOR` privilege needs to be used to be able to fetch replication status; previously this was `REPLICATION CLIENT`. Additionally the suggested source-specification of "any" (`%`) in script and documentation seems a bit broad.

**Comment by Napsty** [comment]
Do you know if that has changed again in MariaDB 10.6? Can't seem to run `SHOW SLAVE STATUS\G` with the following granted privileges: `REPLICA MONITOR, REPLICATION CLIENT`.

**Comment by Napsty** [comment]
Confirmed, setting the privilege `SLAVE MONITOR` (which is an alias for `REPLICA MONITOR`) works. Tested on MariaDB 10.6.
